(()=>{
 'use strict';const $=s=>document.querySelector(s),message=s=>$('#account-message').textContent=s;
 let busy=false,ordersVersion=0;const resetToken=new URLSearchParams(location.hash.slice(1)).get('reset');if(resetToken){history.replaceState(null,'',location.pathname+location.search);$('#account-recovery').hidden=false;}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(n/100);
 async function loadOrders(){const version=++ordersVersion;$('#account-orders-message').textContent='Loading your orders...';$('#account-orders-list').innerHTML='';try{const data=await api('orders');if(version!==ordersVersion)return;$('#account-orders-message').textContent=data.orders.length?'Your orders, newest first.':'You have no orders yet. Browse the catalogue to start your collection.';$('#account-orders-list').innerHTML=data.orders.map(order=>`<article class="checkout-item"><h3>${esc(order.reference)}</h3><p>${esc(new Date(order.createdAt).toLocaleDateString('en-ZA'))} &middot; ${esc(({pending_payment:'Awaiting payment',paid:'Paid',fulfilled:'Fulfilled',cancelled:'Cancelled'})[order.status]||order.status)} &middot; ${order.fulfilment==='delivery'?'Delivery':'Collection'}</p><ul>${order.items.map(item=>`<li>${esc(item.quantity)} &times; ${esc(item.name)}${item.variant?' — '+esc(item.variant):''}</li>`).join('')}</ul><p><strong>Total: ${money(order.totalCents)}</strong></p><a class="btn btn-outline" href="checkout.html?order=${encodeURIComponent(order.reference)}">${order.status==='pending_payment'?'VIEW ORDER / PAYMENT':'VIEW ORDER'}</a></article>`).join('');}catch(e){if(version!==ordersVersion)return;if(e.status===401){show(null);message('Your session expired. Sign in to view your orders.');}else $('#account-orders-message').textContent='Unable to load your orders. Please try again.';}}
 async function api(url,method='GET',body){const r=await fetch('/api/account/'+url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const data=await r.json();if(!r.ok){const e=Error(data.error||'Please try again.');e.status=r.status;throw e;}return data;}
 function show(profile){$('#account-auth').hidden=!!profile;$('#account-security').hidden=!profile;$('#account-profile').hidden=!profile;$('#account-orders').hidden=!profile;if(profile){for(const key of ['name','email','phone'])$('#profile-form').elements[key].value=profile[key];loadOrders();}else{ordersVersion++;$('#account-orders-list').innerHTML='';$('#account-orders-message').textContent='';}}
 $('#refresh-orders').addEventListener('click',loadOrders);
 function wire(id,endpoint,method){$(id).addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const button=e.target.querySelector('button');button.disabled=true;try{const data=await api(endpoint,method,Object.fromEntries(new FormData(e.target)));show(data.profile);e.target.querySelector('[name=password]')?.value&&(e.target.elements.password.value='');message(endpoint==='profile'?'Profile saved. Checkout will use your updated details.':'You are signed in.');if(endpoint!=='profile'&&new URLSearchParams(location.search).get('next')==='checkout'){const reference=new URLSearchParams(location.search).get('order');location.assign('checkout.html'+(/^PM-[A-F0-9]{20}$/.test(reference||'')?'?order='+encodeURIComponent(reference):''));}}catch(e){message(e.message);}finally{busy=false;button.disabled=false;}});}
 wire('#login-form','login','POST');wire('#register-form','register','POST');wire('#profile-form','profile','PUT');
 $('#account-logout').addEventListener('click',async()=>{if(busy)return;busy=true;try{await api('logout','POST');$('#profile-form').reset();show(null);message('You are signed out.');}catch(e){message(e.message);}finally{busy=false;}});
 for(const [id,endpoint] of [['#password-form','password'],['#reset-password-form','reset-password']])$(id).addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const button=e.target.querySelector('button');button.disabled=true;try{const payload=Object.fromEntries(new FormData(e.target));if(endpoint==='reset-password')payload.token=resetToken;await api(endpoint,'POST',payload);e.target.reset();$('#account-recovery').hidden=true;show(null);message('Password updated. All sessions were signed out. Sign in with your new password.');}catch(error){message(error.message);}finally{busy=false;button.disabled=false;}});
 (async()=>{try{const help=await api('help');if(help.supportEmail){const a=document.createElement('a');a.href='mailto:'+help.supportEmail;a.textContent=help.supportEmail;$('#account-help').replaceChildren('Lost access? Request account recovery at ',a,'. We will verify account ownership before issuing a recovery link.');}}catch{}})();
 (async()=>{try{const data=await api('profile');show(data.profile);message('Your saved profile is ready for checkout.');}catch(e){if(e.status===401){show(null);message('Sign in or create your account.');}else message('Accounts are unavailable. Please try again later.');}})();
})();
