'use strict';
const crypto=require('node:crypto'),{promisify}=require('node:util'),rateLimit=require('express-rate-limit');
const scrypt=promisify(crypto.scrypt),{customerFrom}=require('./orders');
const digest=s=>crypto.createHash('sha256').update(s).digest('hex');
async function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return salt+':'+(await scrypt(password,salt,64)).toString('hex');}
async function checkPassword(password,hash){const actual=await hashPassword(password,hash.split(':')[0]);const a=Buffer.from(actual),b=Buffer.from(hash);return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function mountCustomers(app,pool,csrf){
 const secure=process.env.NODE_ENV==='production',cookieOptions={httpOnly:true,secure,sameSite:'lax',path:'/api'};
 const wrap=fn=>async(req,res,next)=>{res.set('Cache-Control','private, no-store');try{await fn(req,res,next);}catch(e){if(e.status)return res.status(e.status).json({error:e.message});next(e);}};
 const requireCustomer=wrap(async(req,res,next)=>{const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('pm_customer='))?.slice(12);if(!token)return res.status(401).json({error:'Sign in to continue checkout.'});const r=await pool.query('SELECT c.id,c.profile FROM customer_sessions s JOIN customers c ON c.id=s.customer_id WHERE s.token_hash=$1 AND s.expires_at>now()',[digest(token)]);if(!r.rowCount)return res.status(401).json({error:'Sign in to continue checkout.'});req.customer=r.rows[0];await pool.query("UPDATE customers SET last_active_at=now() WHERE id=$1 AND last_active_at<now()-interval '1 day'",[req.customer.id]);next();});
 const limiter=require('./rate-limiter').limiter(pool,'account-login',{windowMs:15*60*1000,limit:10,standardHeaders:'draft-7',legacyHeaders:false});
 async function startSession(req,res,user){const previous=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('pm_customer='))?.slice(12);if(previous)await pool.query('DELETE FROM customer_sessions WHERE token_hash=$1',[digest(previous)]);const token=crypto.randomBytes(32).toString('hex');await pool.query('DELETE FROM customer_sessions WHERE expires_at<now()');await pool.query("INSERT INTO customer_sessions(token_hash,customer_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[digest(token),user.id]);res.cookie('pm_customer',token,{...cookieOptions,maxAge:30*86400000});res.json({profile:user.profile});}
 app.post('/api/account/register',limiter,csrf,wrap(async(req,res)=>{const profile=customerFrom(req.body,'collection'),password=req.body.password;if(typeof password!=='string'||password.length<12||password.length>128)return res.status(400).json({error:'Use a password between 12 and 128 characters.'});const id=crypto.randomUUID(),hash=await hashPassword(password);try{await pool.query('INSERT INTO customers(id,profile,email,password_hash) VALUES($1,$2,$3,$4)',[id,JSON.stringify(profile),profile.email,hash]);}catch(e){if(e.code==='23505')return res.status(409).json({error:'An account already uses this email. Sign in instead.'});throw e;}await startSession(req,res,{id,profile});}));
 app.post('/api/account/login',limiter,csrf,wrap(async(req,res)=>{const {email,password}=req.body;if(typeof email!=='string'||typeof password!=='string'||password.length>128)return res.status(401).json({error:'Invalid email or password.'});const r=await pool.query('SELECT id,profile,password_hash FROM customers WHERE email=$1',[email.trim().toLowerCase()]);const dummy='00000000000000000000000000000000:'+ '0'.repeat(128);const valid=await checkPassword(password,r.rows[0]?.password_hash||dummy);if(!r.rowCount||!valid)return res.status(401).json({error:'Invalid email or password.'});await pool.query('UPDATE customers SET last_active_at=now() WHERE id=$1',[r.rows[0].id]);await startSession(req,res,r.rows[0]);}));
 app.get('/api/account/profile',requireCustomer,(req,res)=>res.json({profile:req.customer.profile}));
 app.put('/api/account/profile',csrf,requireCustomer,wrap(async(req,res)=>{const profile=customerFrom(req.body,'collection');if(profile.email!==req.customer.profile.email)return res.status(400).json({error:'Your sign-in email cannot be changed here.'});await pool.query('UPDATE customers SET profile=$2 WHERE id=$1',[req.customer.id,JSON.stringify(profile)]);res.json({profile});}));
 app.post('/api/account/logout',csrf,wrap(async(req,res)=>{const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('pm_customer='))?.slice(12);if(token)await pool.query('DELETE FROM customer_sessions WHERE token_hash=$1',[digest(token)]);res.clearCookie('pm_customer',cookieOptions);res.json({ok:true});}));
 require('./account-security').mountAccountSecurity(app,pool,csrf,requireCustomer,hashPassword,checkPassword);
 return requireCustomer;
}
module.exports={mountCustomers,hashPassword,checkPassword};
